POST https://rvb-backend.onrender.com/casas
Content-Type: application/json

[
  {
    "etapa":"PRUEBA",
    "manzana": "PRUEBA",
    "lote": 100,
    "ubicacion": "ESPECIAL",
    "area_total": 90.25,
    "costo_terreno_m2": 600,
    "costo_construccion_m2": 1697,
    "modulo_m2": 50.6,
    "aplica_calle": true,
    "aplica_parque": false,
    "bono": 46545
  }
]